### ISSUE TITLE
localhost:5443/settings An unhandled exception has occurred

### ISSUE THREAD

**Issue by LEIRONGHUA** [Aguafrommars/TheIdServer#942]
**Describe the bug**
GET URL: https://localhost:5443/api/api/configuration/Aguacongas.TheIdServer.BlazorApp.Models.ServerConfig,%20Aguacongas.TheIdServer.BlazorApp.Infrastructure,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
![image](https://user-images.githubusercontent.com/4002277/215370141-59cbf0ad-a8f4-4306-9e29-5139d7860449.png)
![image](https://user-images.githubusercontent.com/4002277/215370179-2aafe9e3-61f9-4ac8-8702-24f6a12f0989.png)

**Logs**
System.InvalidOperationException: Failed to convert configuration value at 'TokenCleanupInterval' to type 'System.TimeSpan'.
 ---> System.FormatException: "00:05:00" is not a valid value for TimeSpan.
 ---> System.FormatException: String '"00:05:00"' was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetBadTimeSpanFailure()
   at System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.TimeSpan.Parse(String input, IFormatProvider formatProvider)
   at System.ComponentModel.TimeSpanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   .........   
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.Authenticate(HttpContext context, Func`1 next, String basePath, String authicationScheme) in D:\Work\SourceCode\Git\TheIdServer\src\IdentityServer\Duende\Aguacongas.IdentityServer.Admin.Duende\Extensions\EndpointRoutingApplicationBuilderExtensions.cs:line 138

**Platform (please complete the following information):**
 - OS: Windows 11 22H2（22621.1194）
 - .Net Core Version 7.0.102

**Comment by aguacongas** [comment]
Hi, thx to contribute.
I don't reproduce, can you tell me what's your system's culture and in whitch format are serialized `TimeSpan` in this culture ?
The source code uses **en-US**.

**Comment by LEIRONGHUA** [comment]
thank you for your reply.

**System's culture**
`Console.WriteLine("CurrentCultureName is {0}.", System.Globalization.CultureInfo.CurrentCulture.Name);`
`//Print  CurrentCultureName is zh-CN.`

`var timeSpan = TimeSpan.Parse("00:05:00");`
`Console.WriteLine("timeSpan is {0}.", timeSpan.ToString());`
 `//Print timeSpan is  00:05:00`

**Here is the full error log**
[Error.log](https://github.com/Aguafrommars/TheIdServer/files/10544264/Error.log)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'https://localhost:5443/settings'
2. Click on 'Save' (Do not modify any input, just click the save button)
3. Refresh page
4. See error

I think that when saving, the value of the TokenCleanupInterval attribute 05:00:00 was saved as "00:05:00", with a pair of double quotation marks added.
As a result, an abnormal error occurred in the TimeSpan.Parse method
